rostopic pub -r 5 /mtg_agent_bringup_node/agent_0/cmd_vel geometry_msgs/Twist -- '[0.2,0,0]' '[0, 0, 0]'
rostopic pub -r 2 /mtg_agent_bringup_node/agent_0/cmd_vel geometry_msgs/Twist -- '[0,0,0]' '[0,0,1]'
rostopic pub -r 5 /mtg_agent_bringup_node/agent_0/cmd_vel geometry_msgs/Twist -- '[0.2,0,0]' '[0, 0, 0]'
rostopic pub -r 4 /mtg_agent_bringup_node/agent_0/cmd_vel geometry_msgs/Twist -- '[0,0,0]' '[0,0,-1]'
rostopic pub -r 10 /mtg_agent_bringup_node/agent_0/cmd_vel geometry_msgs/Twist -- '[0.2,0,0]' '[0, 0, 0]'
rostopic pub -r 4 /mtg_agent_bringup_node/agent_0/cmd_vel geometry_msgs/Twist -- '[0,0,0]' '[0,0,-1]'
rostopic pub -r 5 /mtg_agent_bringup_node/agent_0/cmd_vel geometry_msgs/Twist -- '[0.2,0,0]' '[0, 0, 0]'
rostopic pub -r 2 /mtg_agent_bringup_node/agent_0/cmd_vel geometry_msgs/Twist -- '[0,0,0]' '[0,0,1]'
rostopic pub -r 5 /mtg_agent_bringup_node/agent_0/cmd_vel geometry_msgs/Twist -- '[0.2,0,0]' '[0, 0, 0]'
